const routesNZ = [
  {
    island: 'north',
    route: 'volcanic loop highway',
    description: '<p>From beautiful vineyards and exhilarating adventures to glittering glowworm caves and geothermal wonders, this itinerary introduces you to some of New Zealand\'s most spectacular attractions.</p><p></p>Walk the famous Tongariro Alpine Crossing, skydive from 15,000ft and visit the famous Hobbiton Movie Set when you journey through the North Island via the Volcanic Loop.</p>',
    days: 7,
    distance: 747, //km
    from: 'Auckland',
    to: 'Auckland',
    imgPath: 'img/routes/north/volcanic-loop-highway/',
    images: ['thumb.jpg', 'volcanic-loop-tongariro-alpine-crossing.jpg', 'maps.png'],
    itinerary: 
      [
        [1, 'Spend the day in Auckland', 0, '', 'rangitoto-summit-track.jpg'], // title, distance, time, image
        [2, 'Hamilton & Waitomo Caves', 199, '2 h 40 min', 'waitomo-glowworm-caves.jpg'],
        [3, 'Pureora Forest & National Park', 143, 'WRONG TIME', 'the-timber-trail.jpg'],
        [4, 'Tongariro Alpine Crossing', 50, '45 min', 'tongariro-alpine-crossing.jpg'],
        [5, 'Explore Taupo', 81, '1 h', 'skydiving-above-the-central-plateau.jpg'],
        [6, 'Spend the day in Rotorua', 0, '', 'te-puia.jpg'],
        [7, 'Return to Auckland via Hobbiton', 196, '3 h 15 min', 'hobbiton-movie-set.jpg'],
      ],
    },
  {
    island: 'north',
    route: 'north island circuit',
    description: '<p>Satisfy your desire to see the best of the North Island with this 10-day round trip through some of New Zealand\'s most fascinating places.</p><p>Travel from Auckland, the vibrant "city of sails", to the seaside villages of Coromandel. Experience Tauranga\'s sunny lifestyle, steaming geothermal attractions in Rotorua, and the vineyards of Gisborne and Napier. Explore creativity in Wellington then head north to discover the mysteries of the Whanganui River. Stroll through gardens in New Plymouth and the magical underworld of Waitomo, before returning to Auckland.</p>',
    days: 10,
    distance: 2063, //km
    from: 'Auckland',
    to: 'Auckland',
    imgPath: 'img/routes/north/north-island-circuit/',
    images: ['thumb.jpg', 'north-island-circuit-bridge-to-nowhere.jpg', 'maps.png'],
    itinerary: 
      [
        [1, 'Auckland to Whitianga', 208, '3 h 20 min', 'driving-creek-railway.jpg'],
        [2, 'Whitianga to Tauranga', 184, '3 h', 'sunrise-on-mt-maunganui.jpg'],
        [3, 'Tauranga to Rotorua', 79, '1 h 10 min', 'tamaki-maori-village.jpg'],
        [4, 'Rotorua to Gisborne via Whakatane', 270, '3 h 40 min', 'white-island.jpg'],
        [5, 'Gisborne to Napier', 214, '3 h', 'hawkes-bay-food-and-wine-classic.jpg'],
        [6, 'Napier to Wellington via Masterton', 230, '4 h 20 min', 'pukaha-mount-bruce.jpg'],
        [7, 'Wellington to Whanganui', 194, '2 h 35 min', 'the-ps-waimarie.jpg'],
        [8, 'Whanganui to New Plymouth', 160, '2 h 15 min', 'egmont-national-park.jpg'],
        [9, 'New Plymouth to Hamilton via Waitomo', 241, '3 h 15 min', 'see-glow-worms.jpg'],
        [10, 'Waitomo to Auckland via Hobbiton', 125, '1 h 50 min', 'hobbiton-movie-set.jpg'],
      ],
    },
  {
    island: 'north',
    route: 'summer rhythm',
    description: '<p>Summer in New Zealand is a time for festivals, with an amazing line up of festivals and events, covering everything from music to wine and culture.</p><p>Of course, it’s not just about the festivals. This 12-day itinerary through the North Island has a ton of ways to experience New Zealand\'s outdoor lifestyle, unique culture and truly epic scenery at every turn. Not to mention all the friendly Kiwis you\'ll meet along the way!</p>',
    days: 12,
    distance: 1188, //km
    from: 'Auckland',
    to: 'Wellington',
    imgPath: 'img/routes/north/summer-rhythm/',
    images: ['thumb.jpg', 'rhythm-and-vines-gisborne.jpg', 'maps.png'],
    itinerary: 
      [
        [1, 'Auckland', 40, '1 h', 'aucklands-unique-nightlife.jpg'],
        [2, 'The Coromandel - 1', 168, '2 h 30 min', 'scallops.jpg'],
        [3, 'The Coromandel - 2', 0, '', ''],
        [4, 'Rotorua - 1', 209, '3 h', 'cultural-performance-at-te-puia.jpg'],
        [5, 'Rotorua - 2', 0, '', ''],
        [6, 'Rotorua - 3', 0, '', ''],
        [7, 'Gisborne - 1', 273, '3 h 40 min', 'rhythm-and-vines.jpg'],
        [8, 'Gisborne - 2', 0, '', ''],
        [9, 'Gisborne - 3', 0, '', ''],
        [10, 'Napier', 214, '3 h', 'hawkes-bay-food-and-wine-classic.jpg'],
        [11, 'Wellington - 1', 230, '4 h 20 min', 'beervana.jpg'],
        [12, 'Wellington - 2', 0, '', ''],
      ],
    },
  {
    island: 'north',
    route: 'cultural kaboom',
    description: '<p>This 20-day itinerary is a backpacker’s dream – cramming in so many unique parts of the Kiwi culture as well as plenty of ways to play.</p><p>Starting in New Zealand’s biggest city, Auckland, you’ll take a North Island circuit that includes adventures like Blackwater rafting in Waitomo Caves, a visit to a marae (Maori meeting house), and tons of geothermal wonders like bubbling mud pools, volcanoes and natural hot springs.</p>',
    days: 20,
    distance: 1087, //km
    from: 'Auckland',
    to: 'Auckland',
    imgPath: 'img/routes/north/cultural-kaboom/',
    images: ['thumb.jpg', 'cultural-kaboom-raglan.jpg', 'maps.png'],
    itinerary: 
      [
        [1, 'Auckland - 1', 0, '', 'rangitoto-summit-track.jpg'],
        [2, 'Auckland - 2', 0, '', ''],
        [3, 'Raglan - 1', 165, '2 h 10 min', 'raglan-beach.jpg'],
        [4, 'Raglan - 2', 0, '', ''],
        [5, 'Waitomo Caves', 92, '1 h 20 min', 'black-water-rafting.jpg'],
        [6, 'Rotorua - 1', 166, '2 h 15 min', 'kerosene-creek.jpg'],
        [7, 'Rotorua - 2', 0, '', ''],
        [8, 'Rotorua - 3', 0, '', ''],
        [9, 'Lake Taupo - 1', 82, '1 h', 'mine-bay.jpg'],
        [10, 'Lake Taupo - 2', 0, '', ''],
        [11, 'Lake Taupo - 3', 0, '', ''],
        [12, 'Whakatane & White Island - 1', 165, '2 h 10 min', 'white-island.jpg'],
        [13, 'Whakatane & White Island - 2', 0, '', ''],
        [14, 'Tauranga & Mount Maunganui - 1', 89, '1 h 10 min', 'kayaking-in-glow-worm-canyon.jpg'],
        [15, 'Tauranga & Mount Maunganui - 2', 0, '', ''],
        [16, 'Hobbiton & Coromandel Peninsula - 1', 0, '', 'cathedral-cove.jpg'],
        [17, 'Hobbiton & Coromandel Peninsula - 2', 0, '', ''],
        [18, 'Hobbiton & Coromandel Peninsula - 3', 0, '', ''],
        [19, 'Auckland via the Pinnacles - 1', 208, '2 h 40 min', 'sunrise-from-the-pinnacles.jpg'],
        [20, 'Auckland via the Pinnacles - 2', 0, '', ''],
      ],
    },

  // South Island Routes  

  {
    island: 'south',
    route: 'south island heritage',
    description: '<p>Discover the fascinating history and natural attractions of the South Island as you journey from Christchurch to Dunedin via Mount Cook on this 5-day heritage journey.</p><p>Explore amazing turquoise lakes and majestic mountain ranges in Mackenzie Country. Visit adventurous Queenstown and the gold-rush towns of Central Otago, before heading towards the coast and the beautiful heritage cities of Dunedin, Oamaru and Christchurch.</p>',
    days: 5,
    distance: 1240, //km
    from: 'Christchurch',
    to: 'Christchurch',
    imgPath: 'img/routes/south/south-island-heritage/',
    images: ['thumb.jpg', 'south-island-heritage-lanarch-castle.jpg', 'maps.png'],
    itinerary: 
      [
        [1, 'Christchurch to Mount Cook via Lake Tekapo', 332, '4 h 10 min', 'the-church-of-the-good-shepherd.jpg'],
        [2, 'Aoraki Mount Cook to Queenstown', 264, '1 h 10 min', 'hot-tubs-omarama.jpg'],
        [3, 'Queenstown to Dunedin via Alexandra', 285, '3 h 30 min', 'lanarch-castle-in-dunedin.jpg'],
        [4, 'Dunedin to Oamaru', 113, '1 h 30 min', 'blue-penguins-oamaru.jpg'],
        [5, 'Oamaru to Christchurch', 250, '3 h 30 min', 'shopping.jpg'],
      ],
    },
  {
    island: 'south',
    route: 'tranzalpine itinerary',
    description: '<p>Spend some time exploring vibrant Christchurch before you head across the Southern Alps to the untamed West Coast.</p><p>Discover a region where temperate rainforest meets glaciers and dramatic coastlines, explore the lakeside resort town of Wanaka, home to the Mt Aspiring National Park and experience the energy of Queenstown, New Zealand\'s adventure capital.</p>',
    days: 6,
    distance: 768, //km
    from: 'Christchurch',
    to: 'Queenstown',
    imgPath: 'img/routes/south/tranzalpine/',
    images: ['thumb.jpg', 'tranzalpine-rob-roy-glacier-mt-aspiring-np.jpg', 'maps.png'],
    itinerary: 
    [
      [1, 'Spend the day in Christchurch', 0, '', 'punting-on-the-avon-river.jpg'],
      [2, 'Christchurch - Greymouth via Arthurs Pass', 244, '3 h', 'tranzalpine-rail-journey.jpg'],
      [3, 'Greymouth to Fox Glacier', 196, '2 h 40 min', 'fox-glacierte-o-tuawe-valley-walk.jpg'],
      [4, 'Fox Glacier to Wanaka', 262, '3 h 15 min', 'roys-peak-track.jpg'],
      [5, 'Wanaka to Queenstown', 112, '1 h 30 min', 'wanaka-queenstown.jpg'],
      [6, 'Explore Queenstown and surrounds', 46, '50 min', 'horse-trekking-in-glenorchy.jpg'],
    ],
    },
  {
    island: 'south',
    route: 'mountains and glaciers',
    description: '<p>Take in some of the South Island’s most stunning natural sights with this 10-day mountains and glaciers itinerary.</p><p>From Christchurch, travel through Arthur’s Pass to the dramatic West Coast. Explore the ancient glaciers, experience nightlife in Wanaka, then make your way to Queenstown, the adventure capital. Cruise majestic Milford Sound and ascend the peaks of Aoraki Mt Cook then travel across the patchwork Canterbury Plains back to Christchurch.</p>',
    days: 10,
    distance: 1912, //km
    from: 'Christchurch',
    to: 'Christchurch',
    imgPath: 'img/routes/south/mountains-glaciers/',
    images: ['thumb.jpg', 'mountains-glaciers-aoraki-mount-cook-national-park.jpg'],
    itinerary: 
    [
      [1, 'Spend the day in Christchurch', 0, '', 'punting-on-the-avon.jpg'],
      [2, 'Christchurch to Greymouth via Arthur\'s Pass', 244, '3 h 20 min', 'tranzalpine-train.jpg'],
      [3, 'Greymouth to Fox Glacier', 196, '2 h 40 min', 'franz-josef-glacier.jpg'],
      [4, 'Fox Glacier to Wanaka', 262, '3 h 15 min ', 'picnic-in-the-mountains.jpg'],
      [5, 'Wanaka to Queenstown', 112, '1 h 30 min', 'paradise-reflections.jpg'],
      [6, 'Spend the day in Queenstown', 46, '50 min', 'the-shotover-jet-in-queenstown.jpg'],
      [7, 'Milford Sound', 287, '3 h 45 min', 'milford-sound.jpg'],
      [8, 'Milford Sound (Return)', 287, '3 h 45 min', ''],
      [9, 'Queenstown to Aoraki Mount Cook', 264, '3 h 15 min', 'tasman-glacier-aoraki-mt-cook.jpg'],
      [10, 'Mount Cook to Christchurch via Lake Tekapo', 332, '4 h 10 min', 'lake-tekapo.jpg'],
    ],
    },
  {
    island: 'south',
    route: 'south island discovery',
    description: '<p>Circle the South Island with this 16-day loop journey, starting in Christchurch.</p><p>From Christchurch follow the coast south through the heritage towns of Oamaru and Dunedin to the remote regions of Southland. In Fiordland discover spectacular Milford Sound before travelling to Queenstown and Wanaka for fun and adventure. Explore soulful West Coast and the sunny cities of Nelson and Blenheim, meet whales up close in Kaikoura and then return to Christchurch to complete the circuit.</p>',
    days: 16,
    distance: 2463, //km
    from: 'Christchurch',
    to: 'Christchurch',
    imgPath: 'img/routes/south/south-island-discovery/',
    images: ['thumb.jpg', 'south-island-discovery-yellow-eyed-penguin-dunedin.jpg', 'maps.png'],
    itinerary: 
    [
      [1, 'Spend the day in Christchurch', 0, '', 'wildlife-encounters.jpg'],
      [2, 'Christchurch to Dunedin', 361, '4 hr 40 min', 'moeraki-boulders.jpg'],
      [3, 'Spend the day in Dunedin', 0, '', 'peninsula-bike-trails.jpg'],
      [4, 'Dunedin to Stewart Island', 205, '2 h 35 min', 'ulva-island.jpg'],
      [5, 'Stewart Island to Te Anau', 159, '2 h', 'te-anau-glowworm-caves.jpg'],
      [6, 'Te Anau to Milford Sound', 287, '1 h 40 min', 'milford-sound.jpg'],
      [7, 'Queenstown', 287, '3 h 45 min', 'ben-lomond-track.jpg'],
      [8, 'Queenstown', 0, '', ''],
      [9, 'Queenstown to Wanaka', 112, '1 h 30 min', 'wild-wire.jpg'],
      [10, 'Wanaka to West Coast Glaciers', 286, '3 h 40 min', 'franz-josef-glacier.jpg'],
      [11, 'Franz Josef to Greymouth', 173, '2 h 15 min', 'greymouth-beach.jpg'],
      [12, 'Greymouth to Marahau', 326, '4 h 40 min', 'punakaiki-pancake-rocks-andamp-blowholes.jpg'],
      [13, 'Marahau to Nelson', 64, '1 h 5 min', 'te-waikoropupu-springs-golden-bay.jpg'],
      [14, 'Nelson to Blenheim', 115, '1 h 35 min', 'winery.jpg'],
      [15, 'Blenheim to Kaikoura', 128, '1 h 50 min', 'kaikoura.jpg'],
      [16, 'Kaikoura to Christchurch', 181, '2 h 45 min', 'antarctic-centre-in-christchurch.jpg'],
    ],
  },

// Both Island Routes

  {
    island: 'both',
    route: 'new zealand highlights',
    description: '<p>Discover some of New Zealand’s most scenic spots with this 14-day highlights itinerary. Gaze in awe at glowworm filled caves and geothermal wonders. Wander through world-class museums and galleries in Wellington.</p><p>Relax on sunny beaches in Nelson and explore glaciers and forests of the wild West Coast, before visiting New Zealand’s adventure capital Queenstown and the truly majestic Milford Sound.</p>',
    days: 14,
    distance: 2444, //km
    from: 'Auckland',
    to: 'Queenstown',
    imgPath: 'img/routes/both/nz-highlights/',
    images: ['thumb.jpg', 'new-zealand-highlights-itinerary-franz-josef-glacier.jpg', 'maps.png'],
    itinerary: 
    [
      [1, 'Spend the day in Auckland', 0, '', 'auckland-helicopter-ride.jpg'],
      [2, 'Auckland - Waitomo Caves', 0, '', 'waitomo-caves.jpg'],
      [3, 'Waitomo Caves - Rotorua', 0, '', 'hells-gate.jpg'],
      [4, 'Spend the day in Rotorua', 0, '', 'te-puia.jpg'],
      [5, 'Rotorua - Taupo', 0, '', 'mine-bay.jpg'],
      [6, 'Taupo - Wellington', 0, '', 'wellington-city.jpg'],
      [7, 'Spend the day in Wellington', 0, '', 'dining-in-wellington-city.jpg'],
      [8, 'Wellington - Picton - Nelson', 0, '', 'marlborough-sounds.jpg'],
      [9, 'Nelson - Greymouth', 0, '', 'rapahoe-beach.jpg'],
      [10, 'Greymouth - Franz Josef Glacier - Fox Glacier', 0, '', 'explore-franz-josef-glacier.jpg'],
      [11, 'Fox Glacier - Wanaka', 0, '', 'lone-tree.jpg'],
      [12, 'Wanaka - Queenstown', 0, '', 'queenstown.jpg'],
      [13, 'Queenstown - Milford Sound', 0, '', 'milford-sound.jpg'],
      [14, 'Milford Sound - Queenstown', 0, '', 'lake-wakatipu-queenstown-trail.jpg'],
    ],
    },
  {
    island: 'both',
    route: 'down the middle',
    description: '<p>This 15-day itinerary through New Zealand is for people who love wild places and outdoor adventures.</p><p>From the geothermal attractions, volcanoes, and river journeys of the North Island, to the towering mountains, mysterious fiords and alpine villages of the South Island. You will be blown away by the variety of adventures and natural attractions on offer with this journey down the middle of New Zealand from Auckland to Invercargill.</p>',
    days: 15,
    distance: 2537, //km
    from: 'Auckland',
    to: 'Invercargill',
    imgPath: 'img/routes/both/down-the-middle/',
    images: ['thumb.jpg', 'down-the-middle-whitewater-rafting.jpg', 'maps.png'],
    itinerary: 
    [
      [1, 'Auckland to Rotorua', 0, '', 'kawakawa-bay-track.jpg'],
      [2, 'Rotorua to Taupo', 0, '', 'skydiving.jpg'],
      [3, 'Taupo to Turangi', 0, '', 'taranaki-falls.jpg'],
      [4, 'Turangi to Whanganui', 0, '', 'the-ps-waimarie.jpg'],
      [5, 'Whanganui to Wellington', 0, '', 'kapiti-island-nature-tours.jpg'],
      [6, 'Spend the day in Wellington', 0, '', 'rimutaka-cycle-trail.jpg'],
      [7, 'Wellington to Nelson', 0, '', 'abel-tasman-national-park.jpg'],
      [8, 'Nelson to St Arnaud', 0, '', 'nelson-lakes.jpg'],
      [9, 'St Arnaud to Hanmer Springs', 0, '', 'quad-biking.jpg'],
      [10, 'Hanmer Springs to Christchurch', 0, '', 'port-hills.jpg'],
      [11, 'Christchurch to Mount Cook Village', 0, '', 'tasman-glacier-aoraki-mt-cook.jpg'],
      [12, 'Mount Cook Village to Queenstown', 0, '', 'shotover-jet.jpg'],
      [13, 'Mount Cook Village to Queenstown', 0, '', ''],
      [14, 'Day trip to Milford Sound', 0, '', 'milford-sound.jpg'],
      [15, 'Milford Sound to Invercargill', 0, '', 'around-the-mountains-cycle.jpg'],
    ],
    },
  {
    island: 'both',
    route: 'top to toe',
    description: '<p>This full-country itinerary provides a total view of New Zealand, taking in all the best attractions. In the North Island you’ll discover beautiful beaches, kauri forests, caves and phenomenal geothermal activity. In the South Island the emphasis is on grand mountain scenery, adventure activities, historic architecture and wildlife encounters.</p>',
    days: 22,
    distance: 3710, //km
    from: 'Auckland',
    to: 'Christchurch',
    imgPath: 'img/routes/both/top-to-toe/',
    images: ['thumb.jpg', 'devils-punchbowl-arthurs-pass.jpg', 'maps.png'],
    itinerary: 
    [
      [1, 'Auckland and Northland', 0, '', 'poor-knights-islands.jpg'],
      [2, 'Auckland and Northland', 0, '', ''],
      [3, 'Auckland and Northland', 0, '', ''],
      [4, 'Auckland and Northland', 0, '', ''],
      [5, 'Spend the day in Auckland', 0, '', 'rangitoto-island-kayak-tour.jpg'],
      [6, 'Auckland - Waitomo Caves', 0, '', 'waitomo-glowworm-caves.jpg'],
      [7, 'Waitomo Caves - Rotorua', 0, '', 'te-puia.jpg'],
      [8, 'Spend the day in Rotorua', 0, '', 'relax-in-the-polynesian-spa.jpg'],
      [9, 'Rotorua - Taupo', 0, '', 'mine-bay.jpg'],
      [10, 'Taupo - Wellington', 0, '', 'tongariro-national-park.jpg'],
      [11, 'Spend the day in Wellington', 0, '', 'cable-car.jpg'],
      [12, 'Wellington to Marlborough', 0, '', 'winery.jpg'],
      [13, 'Marlborough - Hanmer Springs', 0, '', 'hanmer-springs.jpg'],
      [14, 'Hanmer Springs - Christchurch', 0, '', 'christchurch-city.jpg'],
      [15, 'Christchurch - Dunedin', 0, '', 'moeraki-boulders.jpg'],
      [16, 'Dunedin - Stewart Island', 0, '', 'ulva-island.jpg'],
      [17, 'Depart from Stewart Island', 0, '', ''],
      [18, 'Discover Fiordland', 0, '', 'kayaking-in-fiordland.jpg'],
      [19, 'Fiordland - Queenstown', 0, '', 'queenstown.jpg'],
      [20, 'Queenstown - Wanaka', 0, '', 'rippon-vineyard.jpg'],
      [21, 'Wanaka - Fox Glacier', 0, '', 'franz-josef-glacier.jpg'],
      [22, 'Fox Glacier - Arthur\'s Pass - Christchurch', 0, '', 'devils-punchbowl-arthurs-pass.jpg'],
    ],
    },
  {
    island: 'both',
    route: 'ultimate new zealand journey',
    description: '<p>Discover New Zealand on this 32-day ultimate itinerary that will take you from Cape Reinga to Stewart Island and a multitude of places in between.</p><p>Begin in New Zealand\'s biggest city Auckland and explore the beautiful beaches, geothermal attractions and wineries of the North Island before crossing the Cook Strait to the South Island. Here you\'ll meet fascinating wildlife, visit ancient glaciers and majestic fiords, and experience thrilling adventures as you journey the length of the South Island.</p>',
    days: 32,
    distance: 4230, //km
    from: 'Auckland',
    to: 'Christchurch',
    imgPath: 'img/routes/both/ultimate-nz-journey/',
    images: ['thumb.jpg', 'kerosene-creek.jpg', 'maps.png'],
    itinerary: 
    [
      [1, 'Auckland', 0, '', 'auckland.jpg'],
      [2, 'Bay of Islands & Cape Reinga', 0, '', 'waitangi-treaty-ground.jpg'],
      [3, 'Bay of Islands & Cape Reinga', 0, '', ''],
      [4, 'Bay of Islands & Cape Reinga', 0, '', ''],
      [5, 'Bay of Islands & Cape Reinga', 0, '', ''],
      [6, 'Hokianga & Waipoua Forest', 0, '', 'waipoua-forest-footprints-tour.jpg'],
      [7, 'Hokianga & Waipoua Forest', 0, '', ''],
      [8, 'Coromandel & Rotorua', 0, '', 'relax-in-the-polynesian-spa.jpg'],
      [9, 'Coromandel & Rotorua', 0, '', ''],
      [10, 'Coromandel & Rotorua', 0, '', ''],
      [11, 'Taupo & Napier', 0, '', 'hawkes-bay-cycle-trails.jpg'],
      [12, 'Taupo & Napier', 0, '', ''],
      [13, 'Taupo & Napier', 0, '', ''],
      [14, 'Wairarapa & Wellington', 0, '', 'te-papa-museum.jpg'],
      [15, 'Wairarapa & Wellington', 0, '', ''],
      [16, 'Marlborough & Kaikoura', 0, '', 'kayak-tour-with-kaikoura-kayaks.jpg'],
      [17, 'Marlborough & Kaikoura', 0, '', ''],
      [18, 'Marlborough & Kaikoura', 0, '', ''],
      [19, 'The West Coast', 0, '', 'explore-franz-josef-glacier.jpg'],
      [20, 'The West Coast', 0, '', ''],
      [21, 'The West Coast', 0, '', ''],
      [22, 'Queenstown & Wanaka', 0, '', 'queenstown-ledge-bungy.jpg'],
      [23, 'Queenstown & Wanaka', 0, '', ''],
      [24, 'Queenstown & Wanaka', 0, '', ''],
      [25, 'Milford Sound & Te Anau', 0, '', 'milford-sound-cruise.jpg'],
      [26, 'Southland & Stewart Island', 0, '', 'ulva-island-stewart-island.jpg'],
      [27, 'Southland & Stewart Island', 0, '', ''],
      [28, 'The Catlins & Dunedin', 0, '', 'lanarch-castle.jpg'],
      [29, 'The Catlins & Dunedin', 0, '', ''],
      [30, 'Waitaki & Aoraki Mount Cook', 0, '', 'lake-pukaki.jpg'],
      [31, 'Waitaki & Aoraki Mount Cook', 0, '', ''],
      [32, 'Lake Tekapo & Christchurch', 0, '', 'shopping.jpg'],
    ],
    },
];

